### Задание 1
Создайте массив Numpy под названием a размером 5x2, то есть состоящий из 5 строк и 2 столбцов. Первый столбец должен содержать числа 1, 2, 3, 3, 1, а второй - числа 6, 8, 11, 10, 7. Будем считать, что каждый столбец - это признак, а строка - наблюдение. Затем найдите среднее значение по каждому признаку, используя метод mean массива Numpy. Результат запишите в массив mean_a, в нем должно быть 2 элемента.

In [1]:
import numpy as np

# Создаем массив Numpy a
a = np.array([[1, 6],
              [2, 8],
              [3, 11],
              [3, 10],
              [1, 7]])

# Вычисляем среднее значение по каждому признаку
mean_a = np.mean(a, axis=0)

# Выводим результат
print("Массив a:\n", a)
print("\nСреднее значение по каждому признаку (mean_a):\n", mean_a)

Массив a:
 [[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]

Среднее значение по каждому признаку (mean_a):
 [2.  8.4]


### Задание 2
Вычислите массив a_centered, отняв от значений массива “а” средние значения соответствующих признаков, содержащиеся в массиве mean_a. Вычисление должно производиться в одно действие. Получившийся массив должен иметь размер 5x2.

In [2]:
# Вычисляем a_centered
a_centered = a - mean_a

# Выводим результат
print("Массив a:\n", a)
print("\nСреднее значение по каждому признаку (mean_a):\n", mean_a)
print("\nМассив a_centered:\n", a_centered)

Массив a:
 [[ 1  6]
 [ 2  8]
 [ 3 11]
 [ 3 10]
 [ 1  7]]

Среднее значение по каждому признаку (mean_a):
 [2.  8.4]

Массив a_centered:
 [[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]


### Задание 3
Найдите скалярное произведение столбцов массива a_centered. В результате должна получиться величина _centered_spa. Затем поделите a_centered_sp на N-1, где N - число наблюдений.

In [3]:
# Вычисляем скалярное произведение столбцов a_centered
a_centered_sp = np.dot(a_centered[:, 0], a_centered[:, 1])

# Вычисляем число наблюдений
N = a_centered.shape[0]

# Делим a_centered_sp на N-1
a_centered_sp_normalized = a_centered_sp / (N - 1)

# Выводим результат
print("Массив a_centered:\n", a_centered)
print("\nСкалярное произведение столбцов a_centered (a_centered_sp):", a_centered_sp)
print("\nНормализованное скалярное произведение (a_centered_sp_normalized):", a_centered_sp_normalized)

Массив a_centered:
 [[-1.  -2.4]
 [ 0.  -0.4]
 [ 1.   2.6]
 [ 1.   1.6]
 [-1.  -1.4]]

Скалярное произведение столбцов a_centered (a_centered_sp): 8.0

Нормализованное скалярное произведение (a_centered_sp_normalized): 2.0
